version: '3.8'

services:
    nginx:
        image: nginx:alpine
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./certificate.crt:/etc/ssl/certificates/certificate.crt
            - ./private.key:/etc/ssl/certificates/private.key
            - /path/to/existing/react/app:/usr/share/nginx/html
        depends_on:
            - nextjs

    nextjs:
        build: .
        environment:
            - NODE_ENV=production
        command: npm start
